name: Upload release
on:
  release:
    types:
        - created

jobs:
  upload-release:
    permissions: write-all
    name: Upload release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove video
        run: |
          rm -r DemoVideo
          rm -r .github
          rm -r .git
          zip -rj ../BOJ-Workbook-Copy-Paste-Pro-release.zip ./*

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ../BOJ-Workbook-Copy-Paste-Pro-release.zip
          tag: ${{ github.ref }}
